### PR TITLE
Feature/DOC-96

### PR DESCRIPTION
**Pull request by shikhanansi**
I've fixed some broken links to Tiny Docs. Please review.

### CODE REVIEW

**Comment by shikhanansi** [comment]
I've added the .idea files to .gitignore.

**Comment by TheSpyder** [comment]
You need to delete the files, git won't automatically do that - I suggest a rebase and edit commit 37da16896733c3360458627fef498fdff1adcf9e to remove them.

I also recommend ignoring the entire `.idea` folder, not just the files it's created for you thus far.

**Comment by fyrkant** [comment]
I guess this link should be fixed in the other two wrapper components too, tinymce-react and tinymce-angular?

**Comment by shikhanansi** [comment]
I've checked in all the TinyMCE directories in http://stash/projects/TINYMCE, and all the links are working. Please let me know if you find any instance of a broken link.

**Pull request merged**
